name: Build feature

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
    - uses: actions/checkout@v2

    - name: Install Protoc
      uses: zchee/setup-protoc@v1

    - name: Build
      run: |
        ./compile-protobuf.sh
        dotnet build -c Release

    - name: Pack
      run: dotnet pack Sources/SMTSP/SMTSP.csproj -c Release --output packages

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet-Package
        path: packages
