name: Build develop

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Protoc
      uses: zchee/setup-protoc@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build
      run: |
        ./compile-protobuf.sh
        dotnet build -c Release

    - name: Get Previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.0

    - name: Pack
      run: dotnet pack Sources/SMTSP/SMTSP.csproj -c Release -p:PackageVersion='${{ steps.previoustag.outputs.tag }}-develop.${{ github.run_number }}' --output packages

    - name: Upload to GitHub registry
      run: |
        dotnet nuget add source --username InterShare --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/InterShare/index.json"
        dotnet nuget push "packages/SMTSP.${{ steps.previoustag.outputs.tag }}-develop.${{ github.run_number }}.nupkg" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "github"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet-Package
        path: packages
