name: Build feature

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    name: Build feature
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Protoc
      uses: zchee/setup-protoc@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: |
        ./compile-protobuf.sh

        dotnet workload restore
        dotnet build -c Release

    - name: Pack
      run: dotnet pack Sources/SMTSP/SMTSP.csproj -c Release --output packages

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet-Package
        path: packages
