name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        default: "0.0.0"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: dotnet build -c Release

    - name: Publish on NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PACKAGE_NAME: SMTS-Protocol
          PROJECT_FILE_PATH: src/SMTSP/SMTSP.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          VERSION_STATIC: ${{ github.event.inputs.version }}

    - name: Create Release strings
      id: release_strings
      run: |
        echo "RELEASE_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        echo "RELEASE_NAME=Version ${{ github.event.inputs.version }}" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}